#!/bin/bash

# Source directory
source_dir="/home/kip/Documents/journal"

# Destination directory
dest_dir="/home/kip/Documents/ob_journal"

# Create destination directory if it doesn't exist
# mkdir -p "$dest_dir"

# Loop through all files in the source directory
for file in "$source_dir"/*; do
    # Extract the filename without the directory path
    filename=$(basename "$file")
    
    # Copy the file to the destination directory with a new extension
    cp "$file" "$dest_dir/${filename}.md"
done

